# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - bookstore-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Java environment
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Build the application with Maven
      - name: Build with Maven
        run: mvn clean install

      # Debug: Check contents of the target directory
      - name: Check target directory
        run: |
          echo "Checking target directory contents:"
          ls -alh ${{ github.workspace }}/target

      # Upload artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Debug: Check contents of the downloaded artifact
      - name: List downloaded artifacts
        run: ls -alh ${{ github.workspace }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bookstore-app' # Ensure the app name is correct
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_013B8B1BA24F4A698F615AB1BD48D1C9 }}

      - name: List deployed files
        run: curl -u "$bookstore-app:KPFxdJ6qWl2HxSaBnuNTfolie7H9fnSM0Gyvk9smZ3aXbKkM7sfnnBdc7gdi" \
         https://bookstore-app.scm.canadacentral-01.azurewebsites.net/api/command \
         -d '{"command":"ls /home/site/wwwroot"}' \
         -H "Content-Type: application/json"

